use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Kalanhall/Specs.git'

platform :ios, '9.0'

target 'KLUserInfoManager_Example' do
  pod 'KLUserInfoManager', :path => '../'
  pod 'YKWoodpecker'

  target 'KLUserInfoManager_Tests' do
    inherit! :search_paths

    
  end
end
